/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CODIGOS;

import java.awt.AWTException;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.LineNumberReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ismael Ribeiro
 */
public class Janela_Principal extends javax.swing.JFrame {
    
    public Uma_Frase f1;
    public Duas_Frases f2;
    public Tres_Frases f3;
    
    public String letra;
    public String pasta_do_programa = "Marion";
    public static String frase;
    public static String frase_completa;
    public static String arquivo;
    
    public static int qtdLinha;
    
    public static String[] palavras;
    
    public File dir;

    /**
     * Creates new form Janela_Principal
     */
    public Janela_Principal() {
        
        f1 = new Uma_Frase();
        f2 = new Duas_Frases();
        f3 = new Tres_Frases();
        
        initComponents();
    }
    
    public void mostraMensagem(String mensagem, String titulo){
        JOptionPane.showMessageDialog(null,mensagem,titulo,JOptionPane.WARNING_MESSAGE);
    }
    
    public void arquivos(String arquivo) throws FileNotFoundException, IOException{
        
    String unidades_possiveis[] = {"A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"};
    
    dir = new File(letra+":\\"+pasta_do_programa);
    
    if(!dir.exists()){
            for(int i=0; i < unidades_possiveis.length; i++){
                letra = unidades_possiveis[i];
                dir = new File(letra+":\\"+pasta_do_programa);
            if(!dir.exists()){
                //mostraMensagem("O diretório "+pasta_do_programa+" não existe na unidade "+letra+":", arquivo);
            }
            if(dir.exists()){
            i = unidades_possiveis.length;
            }
            if(letra.equals("Z")){
                mostraMensagem("O diretório "+pasta_do_programa+" não existe em lugar nenhum.","Aviso");
        }
    }
}
    
    File arq = new File(dir,arquivo+".txt");
    
    if(!arq.exists() && !arquivo.equals("")){
        mostraMensagem("O arquivo "+arquivo+" não existe na unidade "+letra, "Aviso");
        System.exit(0);
    }
    
    //==========================================================================
    //CONTA A QUANTIDADE DE LINHAS DO ARQUIVO TXT
    File arquivoLeitura = new File(dir,arquivo+".TXT");
    LineNumberReader linhaLeitura = new LineNumberReader(new FileReader(arquivoLeitura));
    linhaLeitura.skip(arquivoLeitura.length());
    qtdLinha = linhaLeitura.getLineNumber();
    palavras = new String[(qtdLinha+1)];
    //==========================================================================
    
        try {
            
            FileReader fileReader = new FileReader(arq);
            BufferedReader bufferedReader = new BufferedReader(fileReader);
            
        try {
            
            for(int i = 0; i < (qtdLinha+1); i++){
                palavras[i] = bufferedReader.readLine();
            }
            
        } catch (IOException ex) {
            Logger.getLogger(Janela_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Janela_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        TEXTO_ARQUIVO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TEXTO_REPETIR = new javax.swing.JTextField();
        BOTAO_START = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Marion - By Ismael Ribeiro");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setText("Arquivo");

        TEXTO_ARQUIVO.setToolTipText("Digite o nome do arquivo a ser executado");

        jLabel3.setText("Repetir");

        TEXTO_REPETIR.setToolTipText("Digite quantas vezes o programa deve repetir a ação");

        BOTAO_START.setText("Start");
        BOTAO_START.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_STARTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TEXTO_REPETIR, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BOTAO_START)
                        .addGap(0, 162, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TEXTO_ARQUIVO)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEXTO_ARQUIVO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TEXTO_REPETIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOTAO_START))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BOTAO_STARTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_STARTActionPerformed
        // TODO add your handling code here:
        if(TEXTO_ARQUIVO.getText().equals("") && TEXTO_REPETIR.getText().equals("")){
            mostraMensagem("Digite as informações necessárias", "Aviso");
        }
        else
        if(TEXTO_ARQUIVO.getText().equals("")){
            mostraMensagem("Digite o nome do arquivo a ser executado", "Aviso");
        }
        else
        if(TEXTO_REPETIR.getText().equals("")){
            mostraMensagem("Digite quantas vezes o programa deve repetir a ação", "Aviso");
        }
        
        int repeticoes = Integer.parseInt(TEXTO_REPETIR.getText());
        
        for(int k =0; k < repeticoes; k++){//FOR
        
        arquivo = TEXTO_ARQUIVO.getText();
        
        /////////////
        try {
            arquivos(arquivo);
        } catch (IOException ex) {
            Logger.getLogger(Janela_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for(int i = 0; i < (qtdLinha+1); i++){
                frase = palavras[i];
                
                frase_completa = frase;
                
                frase = frase.replace(" ",";");
                String[] s = frase.split(";");
            
                String[] palavras_separadas = new String[s.length];
        
                for(int j = 0; j < s.length; j++){
                    palavras_separadas[j] = s[j];
                }
                
                if(s.length == 1){
                    try {
                        f1.Uma_Frase(palavras_separadas[0]);
                    } catch (AWTException ex) {
                        Logger.getLogger(Janela_Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else
                if((s.length == 2)){
                    try {
                        f2.Duas_Frases(palavras_separadas[0], palavras_separadas[1]);
                    } catch (AWTException ex) {
                        Logger.getLogger(Janela_Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else
                if((s.length >= 3)){
                    try {
                        f3.Tres_Frases(palavras_separadas[0], palavras_separadas[1], palavras_separadas[2]);
                    } catch (AWTException ex) {
                        Logger.getLogger(Janela_Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
        }/////////
        
        }//FOR
        
    }//GEN-LAST:event_BOTAO_STARTActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        KeyboardFocusManager.getCurrentKeyboardFocusManager()
            .addKeyEventDispatcher(new KeyEventDispatcher() {
                @Override
                public boolean dispatchKeyEvent(KeyEvent event) {
                    if(event.getID() == KeyEvent.KEY_RELEASED 
                       && event.getKeyCode() == KeyEvent.VK_ENTER){
                        BOTAO_STARTActionPerformed(null);
                           return true;
                     }
                     return false;
                }
        }); 
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTAO_START;
    private javax.swing.JTextField TEXTO_ARQUIVO;
    private javax.swing.JTextField TEXTO_REPETIR;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
